baseURL = "https://Cy83rTR0n.github.io/blog-rev/"
languageCode = "en-us"
title = "Cy83rTR0n's Blog"
theme = "m10c"

[params]
  author = "Cy83rTR0n"
  description = "A blog about all things technical."

  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/Cy83rTR0n"

  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/_Cy83rTR0n"